sonar.projectKey=VistaJobs
sonar.projectName=VistaJobs
sonar.working.directory=/home/sai424/VistaJobs/JBP/.sonarqube/out/.sonar
sonar.projectBaseDir=/home/sai424/VistaJobs/JBP
sonar.pullrequest.cache.basepath=/home/sai424/VistaJobs/JBP

71057C89-858F-4BF7-B7C5-B824345BEE43.sonar.projectKey=VistaJobs:71057C89-858F-4BF7-B7C5-B824345BEE43
71057C89-858F-4BF7-B7C5-B824345BEE43.sonar.projectName=JBP
71057C89-858F-4BF7-B7C5-B824345BEE43.sonar.projectBaseDir=/home/sai424/VistaJobs/JBP
71057C89-858F-4BF7-B7C5-B824345BEE43.sonar.sourceEncoding=utf-8
71057C89-858F-4BF7-B7C5-B824345BEE43.sonar.tests=
71057C89-858F-4BF7-B7C5-B824345BEE43.sonar.sources=\
"/home/sai424/VistaJobs/JBP/Controllers/AdminController.cs",\
"/home/sai424/VistaJobs/JBP/Controllers/ApplicationsController.cs",\
"/home/sai424/VistaJobs/JBP/Controllers/AuthController.cs",\
"/home/sai424/VistaJobs/JBP/Controllers/CandidatesController.cs",\
"/home/sai424/VistaJobs/JBP/Controllers/DigilockerController.cs",\
"/home/sai424/VistaJobs/JBP/Controllers/JobsController.cs",\
"/home/sai424/VistaJobs/JBP/Controllers/VerificationController.cs",\
"/home/sai424/VistaJobs/JBP/Data/ApplicationDbContext.cs",\
"/home/sai424/VistaJobs/JBP/DTOs/LoginDto.cs",\
"/home/sai424/VistaJobs/JBP/DTOs/OtpDtos.cs",\
"/home/sai424/VistaJobs/JBP/DTOs/RegisterDto.cs",\
"/home/sai424/VistaJobs/JBP/DTOs/VerificationRequest.cs",\
"/home/sai424/VistaJobs/JBP/Migrations/20260604082346_intiadb.cs",\
"/home/sai424/VistaJobs/JBP/Migrations/20260604082346_intiadb.Designer.cs",\
"/home/sai424/VistaJobs/JBP/Migrations/20260629073000_AddGoogleAuthAndEmailOtp.cs",\
"/home/sai424/VistaJobs/JBP/Migrations/20260629073000_AddGoogleAuthAndEmailOtp.Designer.cs",\
"/home/sai424/VistaJobs/JBP/Migrations/ApplicationDbContextModelSnapshot.cs",\
"/home/sai424/VistaJobs/JBP/Models/Candidate.cs",\
"/home/sai424/VistaJobs/JBP/Models/EmailOtpVerification.cs",\
"/home/sai424/VistaJobs/JBP/Models/EmploymentHistory.cs",\
"/home/sai424/VistaJobs/JBP/Models/JobApplication.cs",\
"/home/sai424/VistaJobs/JBP/Models/Jobs.cs",\
"/home/sai424/VistaJobs/JBP/Models/Register.cs",\
"/home/sai424/VistaJobs/JBP/Models/SurepassResponse.cs",\
"/home/sai424/VistaJobs/JBP/Models/UanVerificationResult.cs",\
"/home/sai424/VistaJobs/JBP/Models/User.cs",\
"/home/sai424/VistaJobs/JBP/Models/VerificationLog.cs",\
"/home/sai424/VistaJobs/JBP/Program.cs",\
"/home/sai424/VistaJobs/JBP/Services/DigiLockerGateway.cs",\
"/home/sai424/VistaJobs/JBP/Services/DigiLockerOptions.cs",\
"/home/sai424/VistaJobs/JBP/Services/EmailService.cs",\
"/home/sai424/VistaJobs/JBP/Services/EpfoOptions.cs",\
"/home/sai424/VistaJobs/JBP/Services/VerificationProviders/IEpfoVerificationProvider.cs",\
"/home/sai424/VistaJobs/JBP/Services/VerificationProviders/SurepassEpfoProvider.cs",\
"/home/sai424/VistaJobs/JBP/Services/VerificationService.cs",\
"/home/sai424/VistaJobs/JBP/obj/Debug/net8.0/JBP.GlobalUsings.g.cs",\
"/home/sai424/VistaJobs/JBP/obj/Debug/net8.0/.NETCoreApp,Version=v8.0.AssemblyAttributes.cs",\
"/home/sai424/VistaJobs/JBP/obj/Debug/net8.0/JBP.AssemblyInfo.cs",\
"/home/sai424/VistaJobs/JBP/obj/Debug/net8.0/VistaJobsApi.MvcApplicationPartsAssemblyInfo.cs",\
"/home/sai424/VistaJobs/JBP/appsettings.json",\
"/home/sai424/VistaJobs/JBP/Dockerfile",\
"/home/sai424/VistaJobs/JBP/Frontend/about.html",\
"/home/sai424/VistaJobs/JBP/Frontend/assets/vistajobs-logo.png",\
"/home/sai424/VistaJobs/JBP/Frontend/contact.html",\
"/home/sai424/VistaJobs/JBP/Frontend/css/forms.css",\
"/home/sai424/VistaJobs/JBP/Frontend/css/style.css",\
"/home/sai424/VistaJobs/JBP/Frontend/index.html",\
"/home/sai424/VistaJobs/JBP/Frontend/js/app.js",\
"/home/sai424/VistaJobs/JBP/Frontend/js/site-loader.js",\
"/home/sai424/VistaJobs/JBP/JBP.http",\
"/home/sai424/VistaJobs/JBP/Jenkinsfile",\
"/home/sai424/VistaJobs/JBP/PROJECT_FLOW.md",\
"/home/sai424/VistaJobs/JBP/Uploads/3296343f-d93b-4af0-8358-2134092eacd2_Ishwarya_Resume.pdf",\
"/home/sai424/VistaJobs/JBP/Uploads/371d61eb-fad9-40fb-8a66-79a5afdc68a5_Ishwarya_Resume.pdf",\
"/home/sai424/VistaJobs/JBP/Uploads/397eeb04-1cb4-40ea-88cc-84d602bf01db_Ishwarya_Resume.pdf",\
"/home/sai424/VistaJobs/JBP/Uploads/42122a52-fb99-462f-9d25-b2ced2c03b0e_Ishwarya_Resume.pdf",\
"/home/sai424/VistaJobs/JBP/Uploads/4ceaada9-0167-4f4e-98df-ad2fc52b8b6e_Ishwarya_Resume.pdf",\
"/home/sai424/VistaJobs/JBP/Uploads/5c1b4b92-17ce-40a3-8a2a-f13fc72cf2b6_Ishwarya_Resume.pdf",\
"/home/sai424/VistaJobs/JBP/Uploads/86703f5c-33cb-410a-a366-7530a5ece958_Ishwarya_Resume.pdf",\
"/home/sai424/VistaJobs/JBP/Uploads/b3165074-1063-47e0-9317-115aa82b0a53_Ishwarya_Resume.pdf",\
"/home/sai424/VistaJobs/JBP/Uploads/c03b9d68-04b9-44b1-ae8e-2c5cc7b24265_Ishwarya_Resume.pdf",\
"/home/sai424/VistaJobs/JBP/Uploads/d1c4e2ff-5fde-4b8f-bd1f-68e13dafd930_Ishwarya_Resume.pdf",\
"/home/sai424/VistaJobs/JBP/Uploads/e75548af-d39e-44a7-ba60-c784751898a7_Ishwarya_Resume.pdf",\
"/home/sai424/VistaJobs/JBP/Properties/launchSettings.json",\
"/home/sai424/VistaJobs/JBP/obj/JBP.csproj.nuget.dgspec.json",\
"/home/sai424/VistaJobs/JBP/obj/project.assets.json",\
"/home/sai424/VistaJobs/JBP/bin/Debug/net8.0/appsettings.json",\
"/home/sai424/VistaJobs/JBP/bin/Debug/net8.0/VistaJobsApi.deps.json",\
"/home/sai424/VistaJobs/JBP/bin/Debug/net8.0/VistaJobsApi.runtimeconfig.json",\
"/home/sai424/VistaJobs/JBP/obj/Debug/net8.0/JBP.sourcelink.json",\
"/home/sai424/VistaJobs/JBP/obj/Debug/net8.0/staticwebassets.build.json"

71057C89-858F-4BF7-B7C5-B824345BEE43.sonar.cs.analyzer.projectOutPaths=\
"/home/sai424/VistaJobs/JBP/.sonarqube/out/0"
71057C89-858F-4BF7-B7C5-B824345BEE43.sonar.cs.roslyn.reportFilePaths=\
"/home/sai424/VistaJobs/JBP/.sonarqube/out/0/Issues.json"

71057C89-858F-4BF7-B7C5-B824345BEE43.sonar.working.directory=/home/sai424/VistaJobs/JBP/.sonarqube/out/.sonar/mod0
sonar.host.url=http://localhost:9000
sonar.visualstudio.enable=false

sonar.modules=71057C89-858F-4BF7-B7C5-B824345BEE43

