// <auto-generated />
using JBP.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace JBP.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260629073000_AddGoogleAuthAndEmailOtp")]
    partial class AddGoogleAuthAndEmailOtp
    {
    }
}
